[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "kumoai>=2.6.0",
    "numpy>=2.3.2",
    "pandas>=2.3.1",
    "pytz>=2025.2",
]
